version: 0.2.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(product_version)'
  assembly_file_version: '$(assembly_version)'
install:
- ps: >-
    $env:rev = git rev-list HEAD --count

    $env:assembly_version = "$env:appveyor_build_version.$env:rev"

    if ($env:appveyor_repo_tag -eq $True) { $env:product_version = ($env:appveyor_repo_tag_name).Substring(1) }

    else { $env:product_version = "$env:appveyor_build_version.$env:rev-$env:appveyor_repo_branch-$env:appveyor_repo_commit" }
    
    Write-Host -Backgroundcolor Green -Foregroundcolor White "Assembly Version: $env:assembly_version"

    Write-Host -Backgroundcolor Green -Foregroundcolor White " Product Version: $env:product_version"
before_build:
- ps: nuget restore MyExpression.sln
build:
  project: MyExpression.sln
  verbosity: minimal
artifacts:
- path: MyExpression.Core\bin\Release\MyExpression.Core.dll
  name: MyExpression.Core.dll
- path: MyExpression.Console\bin\Release\MyExpression.Console.exe
  name: MyExpression.Console.exe
- path: \
  name: MyExpression 
- path: MyExpression.Core\bin\Release\
  name: MyExpression.Core
- path: MyExpression.Core.Tests\bin\Release\
  name: MyExpression.Core.Tests
- path: MyExpression.Console\bin\Release\
  name: MyExpression.Console
- path: MyExpression.Wpf\bin\Release\
  name: MyExpression.Wpf
- path: TestResult.xml
  name: TestResult
notifications:
- provider: Email
  to:
  - 79232809414@ya.ru
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
after_build:
- ps: >-
    Remove-Item packages -Recurse

    Remove-Item (Get-ChildItem -Recurse -Include nunit.framework.xml)
deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: MyExpression $(appveyor_repo_tag_name)
  description: $(appveyor_repo_tag_name) $(appveyor_build_version).$(rev)
  auth_token:
    secure: Npd8Pdh2luH0INNPoAQXoPC2g71ZM39Ys1Cu842ZZaRFt6B45Or6vy1bV10x0oSn
  artifact: MyExpression; MyExpression.Core.dll; MyExpression.Console.exe; MyExpression.Wpf
  draft: false
  prerelease: true
  on:
    branch: develop
    appveyor_repo_tag: true
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: MyExpression $(appveyor_repo_tag_name)
  description: $(appveyor_repo_tag_name) $(appveyor_build_version).$(rev)
  auth_token:
    secure: Npd8Pdh2luH0INNPoAQXoPC2g71ZM39Ys1Cu842ZZaRFt6B45Or6vy1bV10x0oSn
  artifact: MyExpression; MyExpression.Core.dll; MyExpression.Console.exe; MyExpression.Wpf
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true