version: 0.1.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.$(rev)'
  assembly_file_version: '{version}.$(rev)'
  assembly_informational_version: '{version}.$(rev)'
install:
- ps: >-
    $env:rev = git rev-list HEAD --count

    Write-Host -Backgroundcolor Green -Foregroundcolor White Version:' '$env:appveyor_build_version.$env:rev
before_build:
- ps: nuget restore MyExpression.sln
build:
  project: MyExpression.sln
  verbosity: minimal
artifacts:
- path: MyExpression.Core\bin\Release\MyExpression.Core.dll
  name: MyExpression.Core.dll
- path: MyExpression.Console\bin\Release\MyExpression.Console.exe
  name: MyExpression.Console.exe
- path: \
  name: MyExpression 
- path: MyExpression.Core\bin\Release\
  name: MyExpression.Core
- path: MyExpression.Core.Tests\bin\Release\
  name: MyExpression.Core.Tests
- path: MyExpression.Console\bin\Release\
  name: MyExpression.Console
- path: TestResult.xml
  name: TestResult
notifications:
- provider: Email
  to:
  - 79232809414@ya.ru
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
after_build:
- ps: >-
    Remove-Item packages -Recurse

    Remove-Item (Get-ChildItem -Recurse -Include nunit.framework.xml)
deploy:
  tag: $(appveyor_repo_tag_name)
  release: MyExpression $(appveyor_repo_tag_name)
  description: $(appveyor_repo_tag_name) $(appveyor_build_version).$(rev)
  provider: GitHub
  auth_token:
    secure: Npd8Pdh2luH0INNPoAQXoPC2g71ZM39Ys1Cu842ZZaRFt6B45Or6vy1bV10x0oSn
  artifact: MyExpression; MyExpression.Core.dll; MyExpression.Console.exe
  prerelease: true
  on:
    branch: develop
    appveyor_repo_tag: true