version: 0.3.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- ps: >-
    scripts\version.ps1

    scripts\patching.ps1
before_build:
- ps: nuget restore MyExpression.sln
build:
  project: MyExpression.sln
  verbosity: minimal
after_build:
- ps: >-
    scripts\removemeta.ps1

    scripts\binaries.ps1
artifacts:
- path: MyExpression.Core\bin\Release\MyExpression.Core.dll
  name: MyExpression.Core.dll
- path: MyExpression.Console\bin\Release\MyExpression.Console.exe
  name: MyExpression.Console.exe
- path: \
  name: MyExpression_All_Files
- path: MyExpression.Core\bin\Release\
  name: MyExpression.Core
- path: MyExpression.Core.Tests\bin\Release\
  name: MyExpression.Core.Tests
- path: MyExpression.Console\bin\Release\
  name: MyExpression.Console
- path: MyExpression.Wpf\bin\Release\
  name: MyExpression.Wpf
- path: bin
  name: MyExpression
- path: TestResult.xml
  name: TestResult
deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: MyExpression $(appveyor_repo_tag_name)
  description: $(appveyor_repo_tag_name) $(assembly_version)
  auth_token:
    secure: Npd8Pdh2luH0INNPoAQXoPC2g71ZM39Ys1Cu842ZZaRFt6B45Or6vy1bV10x0oSn
  artifact: MyExpression; MyExpression_All_Files
  draft: false
  prerelease: true
  on:
    branch: develop
    appveyor_repo_tag: true
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: MyExpression $(appveyor_repo_tag_name)
  description: $(appveyor_repo_tag_name) $(assembly_version)
  auth_token:
    secure: Npd8Pdh2luH0INNPoAQXoPC2g71ZM39Ys1Cu842ZZaRFt6B45Or6vy1bV10x0oSn
  artifact: MyExpression; MyExpression_All_Files
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true