version: 0.1.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.$(rev)'
  assembly_file_version: '{version}.$(rev)'
  assembly_informational_version: '{version}.$(rev)'
install:
- ps: $env:rev = git rev-list HEAD --count
before_build:
- ps: nuget restore MyExpression.sln
build:
  project: MyExpression.sln
  verbosity: minimal
artifacts:
- path: TestResult.xml
  name: TestResult
- path: MyExpression.Core\bin\Release\
  name: MyExpression.Core $(appveyor_build_version).$(rev)
- path: MyExpression.Core.Tests\bin\Release\
  name: MyExpression.Core.Tests $(appveyor_build_version).$(rev)
- path: MyExpression.Console\bin\Release\
  name: MyExpression.Console $(appveyor_build_version).$(rev)
- path: \
  name: MyExpression $(appveyor_build_version).$(rev)
- path: MyExpression.Core\bin\Release\MyExpression.Core.dll
  name: MyExpression.Core.dll $(appveyor_build_version).$(rev)
notifications:
- provider: Email
  to:
  - 79232809414@ya.ru
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
deploy:
  tag: v$(APPVEYOR_REPO_TAG_NAME)
  release: MyExpression v$(appveyor_build_version).$(rev)
  description: $(appveyor_build_version).$(rev) v$(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: Npd8Pdh2luH0INNPoAQXoPC2g71ZM39Ys1Cu842ZZaRFt6B45Or6vy1bV10x0oSn
  artifact: MyExpression $(appveyor_build_version).$(rev); MyExpression.Core $(appveyor_build_version).$(rev); MyExpression.Console $(appveyor_build_version).$(rev); MyExpression.Core.Tests $(appveyor_build_version).$(rev); MyExpression.Core.dll $(appveyor_build_version).$(rev)
  prerelease: true
  on:
    branch: develop
    appveyor_repo_tag: true