version: 0.2.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- ps: >-
    $env:rev = git rev-list HEAD --count

    $env:assembly_version = "$env:appveyor_build_version.$env:rev"
    
    Write-Host -Backgroundcolor Green -Foregroundcolor White "Assembly Version: $env:assembly_version"

    $items = Get-ChildItem -Recurse -Include AssemblyInfo.*
    
    foreach ($i in $items) { (Get-Content $i) -replace "111.111.111.111", $env:assembly_version | Set-Content $i }

    foreach ($i in $items) { (Get-Content $i) -replace "222.222.222.222", $env:assembly_version | Set-Content $i }
before_build:
- ps: nuget restore MyExpression.sln
build:
  project: MyExpression.sln
  verbosity: minimal
artifacts:
- path: MyExpression.Core\bin\Release\MyExpression.Core.dll
  name: MyExpression.Core.dll
- path: MyExpression.Console\bin\Release\MyExpression.Console.exe
  name: MyExpression.Console.exe
- path: \
  name: MyExpression 
- path: MyExpression.Core\bin\Release\
  name: MyExpression.Core
- path: MyExpression.Core.Tests\bin\Release\
  name: MyExpression.Core.Tests
- path: MyExpression.Console\bin\Release\
  name: MyExpression.Console
- path: MyExpression.Wpf\bin\Release\
  name: MyExpression.Wpf
- path: TestResult.xml
  name: TestResult
after_build:
- ps: >-
    Remove-Item packages -Recurse

    Remove-Item (Get-ChildItem -Recurse -Include nunit.framework.xml)
deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: MyExpression $(appveyor_repo_tag_name)
  description: $(appveyor_repo_tag_name) $(assembly_version)
  auth_token:
    secure: Npd8Pdh2luH0INNPoAQXoPC2g71ZM39Ys1Cu842ZZaRFt6B45Or6vy1bV10x0oSn
  artifact: MyExpression; MyExpression.Core.dll; MyExpression.Console.exe; MyExpression.Wpf
  draft: false
  prerelease: true
  on:
    branch: develop
    appveyor_repo_tag: true
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: MyExpression $(appveyor_repo_tag_name)
  description: $(appveyor_repo_tag_name) $(assembly_version)
  auth_token:
    secure: Npd8Pdh2luH0INNPoAQXoPC2g71ZM39Ys1Cu842ZZaRFt6B45Or6vy1bV10x0oSn
  artifact: MyExpression; MyExpression.Core.dll; MyExpression.Console.exe; MyExpression.Wpf
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true